name: practice
main: me.merlin.practice.Practice
version: ${project.version}


commands:
  profile:
    description: Get a player profile from database
  add:
    description: Add a player to the database
  kit:
    description: Kit command
  duel:
    description: Duel command
  accept:
    description: Accept a duel
  spawn:
    description: Teleport to spawn
  effect:
    description: Give a player an effect
  state:
    description: get a player state
  builder:
    description: Toggle builder mode
  giveitems:
    description: Give a player the default lobby items
  arena:
    description: Arena command